// ============================================
// Platform Data & Constants
// ============================================

const PLATFORM_DATA = {
  macOS: {
    icon: "🖥️",
    color: "#0071E3",
    colorLight: "#E8F2FE",
    title: "macOS",
    subtitle: "데스크톱 확장",
    difficulty: "낮음",
    difficultyColor: "#34C759",
    method: "Mac Catalyst / iPad 앱 네이티브 포팅",
    timeline: "2~6주",
    criteria: [
      { label: "장시간 작업 필요", desc: "문서 편집, 코딩, 디자인 등 30분 이상 집중 작업", weight: 95, icon: "⏱️" },
      { label: "키보드/마우스 우선 UX", desc: "단축키, 우클릭 메뉴, 드래그 앤 드롭이 핵심 인터랙션", weight: 90, icon: "⌨️" },
      { label: "대화면 정보 밀도", desc: "멀티 패널, 사이드바, 동시에 많은 정보 표시 필요", weight: 85, icon: "📐" },
      { label: "파일 시스템 접근", desc: "로컬 파일 읽기/쓰기, 폴더 관리, 외부 앱 연동", weight: 80, icon: "📁" },
      { label: "백그라운드 상시 실행", desc: "메뉴바 앱, 알림 모니터링, 자동화 작업", weight: 75, icon: "🔄" },
    ],
    goodFit: ["생산성 도구 (노트, 할일, 캘린더)", "클립보드 매니저", "개발자 도구", "미디어 편집", "파일 관리"],
    badFit: ["피트니스/건강 트래커", "카메라 중심 앱", "위치 기반 서비스"],
    realExamples: [
      { app: "Notion", reason: "장시간 문서 작업 → 데스크톱 필수" },
      { app: "Things 3", reason: "키보드 단축키로 빠른 할일 관리" },
      { app: "Fantastical", reason: "넓은 화면에서 캘린더 전체 뷰" },
    ],
    decisionQuestion: "사용자가 이 앱을 30분 이상 연속 사용하는가?",
  },
  watchOS: {
    icon: "⌚",
    color: "#FF375F",
    colorLight: "#FFF0F3",
    title: "watchOS",
    subtitle: "손목 위의 확장",
    difficulty: "중간",
    difficultyColor: "#FF9500",
    method: "watchOS 독립 앱 / Companion 앱",
    timeline: "3~8주",
    criteria: [
      { label: "5초 이내 글랜스 정보", desc: "빠르게 확인하고 끝나는 핵심 정보 (시간, 날씨, 수치)", weight: 95, icon: "👀" },
      { label: "신체 센서 데이터 활용", desc: "심박수, 걸음 수, 운동량 등 HealthKit 연동", weight: 90, icon: "💓" },
      { label: "즉각적 알림/반응", desc: "진동 알림 후 1탭으로 완료되는 액션", weight: 85, icon: "🔔" },
      { label: "컴플리케이션 가치", desc: "워치페이스에 상시 표시할 의미있는 데이터 존재", weight: 80, icon: "⭕" },
      { label: "iPhone 없이 독립 사용", desc: "운동, 외출 시 iPhone 없이도 핵심 기능 사용 가능", weight: 70, icon: "📱" },
    ],
    goodFit: ["건강/피트니스 트래커", "타이머/알림 앱", "간단한 리모컨", "날씨/교통 정보", "투두 체크리스트"],
    badFit: ["콘텐츠 소비 앱", "복잡한 입력이 필요한 앱", "미디어 편집"],
    realExamples: [
      { app: "AutoSleep", reason: "수면 추적 → 손목 센서 필수" },
      { app: "Streaks", reason: "습관 체크 → 1탭 완료" },
      { app: "Citymapper", reason: "다음 정류장 글랜스 정보" },
    ],
    decisionQuestion: "사용자가 5초 이내에 얻을 수 있는 핵심 정보가 있는가?",
  },
  iPadOS: {
    icon: "📱",
    color: "#5856D6",
    colorLight: "#F3F2FE",
    title: "iPadOS",
    subtitle: "태블릿 최적화",
    difficulty: "낮음",
    difficultyColor: "#34C759",
    method: "Adaptive Layout / 멀티태스킹 지원",
    timeline: "1~4주",
    criteria: [
      { label: "멀티태스킹 시너지", desc: "Split View, Slide Over에서 다른 앱과 함께 사용하는 가치", weight: 95, icon: "🪟" },
      { label: "Apple Pencil 활용", desc: "필기, 드로잉, 정밀 선택 등 펜 입력이 가치를 더함", weight: 85, icon: "✏️" },
      { label: "넓은 캔버스 활용", desc: "큰 화면에서 더 많은 콘텐츠/도구를 동시에 표시", weight: 90, icon: "🖼️" },
      { label: "Stage Manager 대응", desc: "자유 크기 윈도우에서도 레이아웃이 잘 동작", weight: 75, icon: "🎭" },
      { label: "외장 키보드 최적화", desc: "Magic Keyboard 연결 시 단축키 및 트랙패드 지원", weight: 80, icon: "⌨️" },
    ],
    goodFit: ["노트/드로잉 앱", "문서 편집기", "미디어 뷰어", "교육/학습 앱", "프레젠테이션 도구"],
    badFit: ["전화 전용 기능", "소형 위젯 앱", "워치 컴패니언 앱"],
    realExamples: [
      { app: "GoodNotes", reason: "Pencil 필기 → iPad 핵심 경험" },
      { app: "LumaFusion", reason: "넓은 타임라인 → 영상 편집 최적" },
      { app: "Procreate", reason: "대형 캔버스 + Pencil 정밀 입력" },
    ],
    decisionQuestion: "큰 화면과 Pencil이 앱 경험을 본질적으로 향상시키는가?",
  },
  tvOS: {
    icon: "📺",
    color: "#64D2FF",
    colorLight: "#F0FBFF",
    title: "tvOS",
    subtitle: "거실 확장",
    difficulty: "중간",
    difficultyColor: "#FF9500",
    method: "tvOS 전용 앱 / AirPlay 지원",
    timeline: "4~10주",
    criteria: [
      { label: "린백 콘텐츠 소비", desc: "소파에 앉아 편하게 감상하는 영상/음악/사진 콘텐츠", weight: 95, icon: "🛋️" },
      { label: "공유 화면 가치", desc: "가족/친구와 함께 큰 화면으로 보는 것이 의미있음", weight: 90, icon: "👨‍👩‍👧‍👦" },
      { label: "시리 리모트 UX", desc: "스와이프, 클릭 중심의 단순 인터랙션으로 충분", weight: 85, icon: "🎮" },
      { label: "대형 디스플레이 임팩트", desc: "55인치+ 화면에서 콘텐츠가 극적으로 향상됨", weight: 80, icon: "🖥️" },
      { label: "iPhone 리모컨 시너지", desc: "iPhone을 세컨드 스크린/컨트롤러로 활용", weight: 70, icon: "📱" },
    ],
    goodFit: ["스트리밍/미디어 앱", "피트니스 (홈트)", "사진 슬라이드쇼", "게임", "교육 영상"],
    badFit: ["텍스트 입력 중심 앱", "위치 기반 앱", "개인 정보 민감 앱"],
    realExamples: [
      { app: "Fitness+", reason: "거실 운동 → 대형 화면 필수" },
      { app: "Infuse", reason: "미디어 라이브러리 → TV 최적" },
      { app: "Alto's Odyssey", reason: "캐주얼 게임 → 대형 화면 몰입" },
    ],
    decisionQuestion: "콘텐츠가 대형 공유 화면에서 더 가치있어지는가?",
  },
  visionOS: {
    icon: "🥽",
    color: "#AC8E68",
    colorLight: "#FAF6F0",
    title: "visionOS",
    subtitle: "공간 컴퓨팅 확장",
    difficulty: "높음",
    difficultyColor: "#FF3B30",
    method: "visionOS 네이티브 / Compatible iPad 앱",
    timeline: "6~16주",
    criteria: [
      { label: "3D 공간 활용 가치", desc: "콘텐츠가 3D 공간에 배치될 때 새로운 경험 제공", weight: 95, icon: "🌐" },
      { label: "몰입형 콘텐츠", desc: "180°/360° 영상, 공간 오디오, 몰입 환경 활용", weight: 90, icon: "🎬" },
      { label: "무한 캔버스 필요", desc: "여러 윈도우를 공간에 자유롭게 배치하는 워크플로우", weight: 85, icon: "♾️" },
      { label: "시선/제스처 자연 UX", desc: "눈과 손으로 조작하는 것이 자연스러운 인터랙션", weight: 80, icon: "👁️" },
      { label: "개인 극장 경험", desc: "대형 가상 스크린에서의 미디어/작업 경험", weight: 75, icon: "🎭" },
    ],
    goodFit: ["3D 모델 뷰어", "몰입형 미디어", "디자인/건축 도구", "교육/시뮬레이션", "명상/웰빙"],
    badFit: ["빠른 유틸리티 앱", "센서 의존 앱", "대중 시장 앱 (아직)"],
    realExamples: [
      { app: "JigSpace", reason: "3D 모델 → 공간에서 실물 크기 확인" },
      { app: "Mindfulness", reason: "몰입 환경 → 명상 경험 극대화" },
      { app: "Freeform", reason: "무한 캔버스 → 공간에 보드 배치" },
    ],
    decisionQuestion: "앱 경험이 3D 공간 배치로 본질적으로 달라지는가?",
  },
};

const FLOW_STEPS = [
  { id: 1, title: "iOS 앱 핵심 가치 정의", desc: "앱의 Core Value Proposition이 무엇인가?", icon: "🎯" },
  { id: 2, title: "사용 맥락 분석", desc: "사용자가 언제, 어디서, 얼마나 사용하는가?", icon: "🔍" },
  { id: 3, title: "플랫폼 시너지 평가", desc: "해당 플랫폼의 고유 기능이 앱 가치를 높이는가?", icon: "⚡" },
  { id: 4, title: "투자 대비 효과 판단", desc: "개발/유지보수 비용 대비 사용자 가치가 충분한가?", icon: "💰" },
  { id: 5, title: "확장 실행", desc: "점진적 확장: 핵심 기능 먼저 → 플랫폼 고유 기능 추가", icon: "🚀" },
];

const DECISION_MATRIX = [
  { factor: "사용 시간", macOS: "◉", watchOS: "◎", iPadOS: "◉", tvOS: "●", visionOS: "●" },
  { factor: "입력 복잡도", macOS: "◉", watchOS: "◎", iPadOS: "●", tvOS: "◎", visionOS: "●" },
  { factor: "화면 크기 의존", macOS: "●", watchOS: "◎", iPadOS: "◉", tvOS: "◉", visionOS: "◉" },
  { factor: "센서 활용", macOS: "◎", watchOS: "◉", iPadOS: "●", tvOS: "◎", visionOS: "●" },
  { factor: "공유 사용", macOS: "◎", watchOS: "◎", iPadOS: "●", tvOS: "◉", visionOS: "◎" },
  { factor: "이동 중 사용", macOS: "◎", watchOS: "◉", iPadOS: "●", tvOS: "◎", visionOS: "◎" },
];

const PRIORITY_ITEMS = [
  { step: "1", title: "iPadOS 최적화", desc: "Adaptive Layout만으로 큰 효과, 최소 투자", color: "#34C759", tag: "Quick Win" },
  { step: "2", title: "macOS (Catalyst)", desc: "iOS 코드 재사용 극대화, 프로 사용자 확보", color: "#0071E3", tag: "High ROI" },
  { step: "3", title: "watchOS 컴패니언", desc: "핵심 글랜스 기능만 구현, 앱 생태계 완성", color: "#FF375F", tag: "Ecosystem" },
  { step: "4", title: "tvOS / visionOS", desc: "콘텐츠 중심 앱만 선별적 확장", color: "#AC8E68", tag: "Strategic" },
];

const PLATFORM_KEYS = ["macOS", "watchOS", "iPadOS", "tvOS", "visionOS"];

// iOS platform data (for unified selector)
const IOS_PLATFORM_DATA = {
  icon: "📱",
  color: "#007AFF",
  colorLight: "#E8F2FE",
  title: "iOS",
  subtitle: "모바일 기반",
  desc: "가장 큰 사용자 기반. 터치 중심 UX, 모바일 최적화.",
  decisionQuestion: "이 앱의 핵심 경험이 모바일 터치 UX에서 출발하는가?",
  difficulty: "-",
  difficultyColor: "#007AFF",
  method: "SwiftUI / UIKit 네이티브",
  timeline: "-",
};

// ============================================
// Cross-Platform Expansion Map
// base -> target 별 확장 전략
// ============================================

const BASE_PLATFORMS = ["iOS", "macOS", "iPadOS", "watchOS", "tvOS", "visionOS"];

const EXPANSION_MAP = {
  iOS: {
    icon: "📱", color: "#007AFF", colorLight: "#E8F2FE",
    desc: "가장 큰 사용자 기반. 터치 중심 UX, 모바일 최적화.",
    expansions: {
      macOS: {
        title: "iOS → macOS",
        difficulty: "중간",
        approach: "Mac Catalyst 또는 SwiftUI 네이티브 포팅",
        keyChanges: [
          "터치 → 마우스/키보드 중심 인터랙션 전환",
          "단일 화면 → 멀티 윈도우/메뉴바 구조",
          "모달 시트 → 패널/인스펙터 패턴",
          "네비게이션 스택 → 사이드바 + 디테일 레이아웃",
        ],
        considerations: "모바일에서 검증된 핵심 워크플로우를 유지하되, 데스크톱 사용자의 생산성 기대치(단축키, 드래그앤드롭, 멀티태스킹)를 충족해야 합니다.",
        effort: 6,
        example: "Things 3 — iPhone의 간결한 할일 관리를 Mac에서 키보드 단축키와 다중 윈도우로 확장",
      },
      iPadOS: {
        title: "iOS → iPadOS",
        difficulty: "낮음",
        approach: "Adaptive Layout + 멀티태스킹 지원",
        keyChanges: [
          "단일 컬럼 → 사이드바/Split View 레이아웃",
          "기본 제스처 → Apple Pencil/트랙패드 입력 추가",
          "전체화면 → Split View/Slide Over 대응",
          "작은 탭바 → 넓은 툴바/사이드바 활용",
        ],
        considerations: "이미 iOS 코드를 공유하므로 가장 적은 노력으로 큰 효과. Adaptive Layout과 Size Class만 잘 대응해도 80%는 완성됩니다.",
        effort: 2,
        example: "Bear — iPhone 노트앱을 iPad에서 3단 레이아웃 + Pencil 드로잉으로 확장",
      },
      watchOS: {
        title: "iOS → watchOS",
        difficulty: "중간",
        approach: "Companion 앱 또는 독립 watchOS 앱",
        keyChanges: [
          "풍부한 UI → 글랜스 가능한 핵심 정보만 추출",
          "자유로운 입력 → Digital Crown/탭 중심 조작",
          "긴 세션 → 5초 이내 인터랙션으로 재설계",
          "시각 중심 → 햅틱/소리 피드백 활용",
        ],
        considerations: "iPhone 앱의 축소판이 아닌, 손목에 최적화된 완전히 새로운 경험을 설계해야 합니다. 가장 중요한 1~2가지 기능만 가져가세요.",
        effort: 5,
        example: "Streaks — iPhone의 습관 트래커를 Watch에서 1탭 체크 + 컴플리케이션으로 축약",
      },
      tvOS: {
        title: "iOS → tvOS",
        difficulty: "높음",
        approach: "tvOS 전용 앱 / AirPlay 지원",
        keyChanges: [
          "터치 → Siri Remote 포커스 기반 네비게이션",
          "개인 화면 → 공유 대형 화면 경험",
          "세밀한 조작 → 단순한 방향키/클릭 UX",
          "세로 스크롤 → 가로 중심 콘텐츠 브라우징",
        ],
        considerations: "TV 시청 맥락(린백, 공유, 거리)에 맞는 콘텐츠 소비 경험을 설계해야 합니다. 텍스트 입력이 많은 기능은 iPhone 리모컨 앱으로 분리하세요.",
        effort: 7,
        example: "WWDC — iPhone의 세션 브라우징을 TV에서 풀스크린 영상 시청 경험으로 전환",
      },
      visionOS: {
        title: "iOS → visionOS",
        difficulty: "높음",
        approach: "Compatible 모드 → 점진적 공간 UI 도입",
        keyChanges: [
          "2D 레이아웃 → 3D 공간 배치 가능성 탐색",
          "터치 → 시선 추적 + 핀치 제스처",
          "고정 화면 → 무한 공간 윈도우 배치",
          "단일 윈도우 → 볼륨/이머시브 스페이스 활용",
        ],
        considerations: "먼저 iPad 호환 모드로 진입한 후, 공간 UI가 실질적 가치를 더하는 기능부터 점진적으로 네이티브화하세요. 3D가 기믹이 아닌 본질적 개선일 때만 투자하세요.",
        effort: 8,
        example: "Freeform — iPhone의 화이트보드를 Vision Pro에서 무한 공간 캔버스로 확장",
      },
    },
  },
  macOS: {
    icon: "🖥️", color: "#0071E3", colorLight: "#E8F2FE",
    desc: "생산성 중심. 키보드/마우스 UX, 멀티윈도우 환경.",
    expansions: {
      iOS: {
        title: "macOS → iOS",
        difficulty: "높음",
        approach: "SwiftUI 공유 또는 iOS 네이티브 재설계",
        keyChanges: [
          "멀티 윈도우 → 단일 화면 네비게이션 스택",
          "메뉴바/단축키 → 탭바/제스처 중심 UX",
          "마우스 정밀도 → 손가락 터치 타겟 (44pt+)",
          "파일 시스템 → 앱 샌드박스/문서 피커",
        ],
        considerations: "데스크톱의 복잡한 워크플로우를 모바일에 우겨넣지 마세요. 이동 중 가장 자주 쓰는 핵심 기능 2~3개만 선별하여 모바일 최적 UX로 완전히 재설계해야 합니다.",
        effort: 8,
        example: "Sketch → 편집은 Mac 전용, 미리보기/협업 리뷰만 iPhone으로 분리",
      },
      iPadOS: {
        title: "macOS → iPadOS",
        difficulty: "중간",
        approach: "Mac Catalyst 역방향 또는 SwiftUI 공유",
        keyChanges: [
          "윈도우 관리 → Stage Manager/Split View 대응",
          "메뉴바 → 터치 친화적 툴바",
          "마우스 hover → 터치 + Pencil 입력 추가",
          "고정 사이드바 → 접이식 사이드바",
        ],
        considerations: "Mac과 iPad은 점점 수렴 중이지만, iPad에서는 터치와 Pencil이 일급 입력입니다. Mac의 복잡한 메뉴를 그대로 옮기지 말고 터치에 최적화된 도구 팔레트로 재구성하세요.",
        effort: 5,
        example: "Affinity Designer — Mac의 벡터 편집을 iPad에서 Pencil 직접 드로잉 경험으로 재해석",
      },
      watchOS: {
        title: "macOS → watchOS",
        difficulty: "높음",
        approach: "핵심 알림/상태 모니터링 전용 Companion",
        keyChanges: [
          "복잡한 대시보드 → 단일 핵심 지표 글랜스",
          "데스크톱 알림 → 손목 햅틱 알림",
          "상세 제어판 → 1~2탭 빠른 액션",
          "지속적 작업 → 상태 확인 후 Mac으로 복귀",
        ],
        considerations: "Mac 앱의 복잡한 기능을 Watch에 넣으려 하지 마세요. '지금 서버 상태가 정상인가?', '빌드가 완료됐나?' 같은 한 가지 핵심 상태만 글랜스로 보여주세요.",
        effort: 6,
        example: "GitHub — Mac에서 코드 리뷰, Watch에서 CI 빌드 상태/PR 알림만 확인",
      },
      tvOS: {
        title: "macOS → tvOS",
        difficulty: "높음",
        approach: "콘텐츠 프레젠테이션 전용 앱",
        keyChanges: [
          "생산 도구 → 결과물 프레젠테이션/소비",
          "정밀 입력 → 리모컨 포커스 네비게이션",
          "작업 중심 → 감상/공유 중심",
          "개인 화면 → 팀/가족 공유 디스플레이",
        ],
        considerations: "Mac에서 '만든' 결과물을 TV에서 '보여주는' 관점으로 접근하세요. 편집 기능은 가져가지 말고, 프레젠테이션/감상에 집중하세요.",
        effort: 7,
        example: "Keynote — Mac에서 제작, Apple TV에서 풀스크린 프레젠테이션",
      },
      visionOS: {
        title: "macOS → visionOS",
        difficulty: "중간",
        approach: "무한 공간 데스크톱 + 몰입형 뷰",
        keyChanges: [
          "물리 모니터 → 가상 무한 디스플레이",
          "마우스/키보드 → 시선/제스처 + 물리 키보드 병행",
          "2D 윈도우 → 공간에 자유 배치된 다중 윈도우",
          "고정 작업 공간 → 맥락별 환경 전환",
        ],
        considerations: "Mac의 멀티윈도우 생산성을 공간 컴퓨팅으로 자연스럽게 확장할 수 있습니다. 기존 Mac 앱이 이미 윈도우 기반이므로, visionOS의 공간 배치와 궁합이 좋습니다.",
        effort: 6,
        example: "Xcode — Mac의 코드 에디터를 Vision Pro에서 다중 모니터급 공간으로 확장",
      },
    },
  },
  iPadOS: {
    icon: "📱", color: "#5856D6", colorLight: "#F3F2FE",
    desc: "터치+Pencil 중심. 크리에이티브/교육에 강점.",
    expansions: {
      iOS: {
        title: "iPadOS → iOS",
        difficulty: "낮음",
        approach: "Adaptive Layout 축소 + 핵심 기능 선별",
        keyChanges: [
          "멀티 컬럼 → 단일 컬럼 네비게이션",
          "Pencil 드로잉 → 손가락 터치로 단순화",
          "넓은 캔버스 → 핀치 줌/패닝으로 대응",
          "Split View → 전체화면 단일 태스크",
        ],
        considerations: "iPad의 넓은 화면에 최적화된 레이아웃을 iPhone에서 자연스럽게 축소해야 합니다. Pencil 전용 기능은 손가락으로도 사용 가능하게 대안을 제공하세요.",
        effort: 3,
        example: "Procreate Pocket — iPad의 프로 드로잉을 iPhone 화면에 맞게 UI를 단순화",
      },
      macOS: {
        title: "iPadOS → macOS",
        difficulty: "중간",
        approach: "Mac Catalyst 또는 SwiftUI 네이티브",
        keyChanges: [
          "터치/Pencil → 마우스/트랙패드 정밀 입력",
          "제스처 기반 → 메뉴바/단축키 체계 추가",
          "전체화면 → 리사이즈 가능한 윈도우",
          "온스크린 팔레트 → 인스펙터/사이드 패널",
        ],
        considerations: "iPad 앱이 이미 큰 화면에 대응하므로 Mac으로의 전환이 비교적 자연스럽습니다. 단, Pencil에 의존하는 핵심 기능은 마우스/트랙패드로 동등한 경험을 제공해야 합니다.",
        effort: 5,
        example: "GoodNotes — iPad Pencil 필기를 Mac에서 트랙패드+타이핑 하이브리드로 확장",
      },
      watchOS: {
        title: "iPadOS → watchOS",
        difficulty: "높음",
        approach: "알림/퀵 액션 전용 미니 앱",
        keyChanges: [
          "넓은 캔버스 → 작은 화면 핵심 정보만",
          "Pencil 입력 → Scribble/음성 입력",
          "비주얼 리치 → 텍스트/아이콘 중심",
          "창작 도구 → 상태 알림/빠른 체크",
        ],
        considerations: "iPad의 크리에이티브 도구를 Watch로 가져가는 건 무리입니다. '작업 알림 받기', '간단한 상태 체크' 정도의 보조 역할로 한정하세요.",
        effort: 7,
        example: "Notion — iPad의 복잡한 문서 편집 대신 Watch에서 할일 체크/리마인더만 제공",
      },
      tvOS: {
        title: "iPadOS → tvOS",
        difficulty: "중간",
        approach: "콘텐츠 감상/프레젠테이션 전용",
        keyChanges: [
          "터치 인터랙션 → 리모컨 포커스 기반",
          "편집/창작 → 결과물 감상/공유",
          "개인 캔버스 → 공유 대형 화면",
          "세밀한 조작 → 브라우징/재생 중심",
        ],
        considerations: "iPad에서 만든 콘텐츠를 TV에서 감상하는 시나리오가 가장 자연스럽습니다. 창작 기능은 제외하고 갤러리/프레젠테이션 뷰어로 접근하세요.",
        effort: 6,
        example: "Keynote — iPad에서 Pencil로 슬라이드 편집, TV에서 청중에게 발표",
      },
      visionOS: {
        title: "iPadOS → visionOS",
        difficulty: "낮음",
        approach: "iPad 호환 모드 → 점진적 공간 UI",
        keyChanges: [
          "2D 캔버스 → 3D 공간 캔버스 확장",
          "Pencil 입력 → 핀치/제스처 입력",
          "고정 화면 → 공간에 띄운 무한 윈도우",
          "평면 콘텐츠 → 3D 오브젝트 배치 가능",
        ],
        considerations: "iPad 앱은 visionOS에서 자동 호환됩니다. 크리에이티브 앱이라면 3D 공간을 캔버스로 활용하는 것이 자연스러운 확장입니다.",
        effort: 4,
        example: "Freeform — iPad의 화이트보드를 Vision Pro 공간에 실물 크기로 펼쳐놓기",
      },
    },
  },
  watchOS: {
    icon: "⌚", color: "#FF375F", colorLight: "#FFF0F3",
    desc: "글랜스 정보 + 건강 센서. 초단시간 인터랙션.",
    expansions: {
      iOS: {
        title: "watchOS → iOS",
        difficulty: "중간",
        approach: "Companion 앱 확장 또는 독립 iOS 앱",
        keyChanges: [
          "글랜스 정보 → 상세 데이터 대시보드",
          "1탭 액션 → 풍부한 설정/커스터마이징",
          "센서 데이터 요약 → 차트/트렌드 분석",
          "단순 알림 → 상세 알림 관리/액션",
        ],
        considerations: "Watch에서 수집한 데이터를 iPhone에서 깊이 있게 분석하고 관리하는 허브 역할로 설계하세요. Watch는 수집, iPhone은 분석/설정의 역할 분담이 핵심입니다.",
        effort: 5,
        example: "AutoSleep — Watch가 수면 데이터를 수집, iPhone에서 상세 수면 패턴 분석",
      },
      macOS: {
        title: "watchOS → macOS",
        difficulty: "높음",
        approach: "데이터 분석 대시보드 + 메뉴바 앱",
        keyChanges: [
          "실시간 센서 → 장기 데이터 트렌드 뷰",
          "손목 글랜스 → 메뉴바 상시 모니터링",
          "모바일 차트 → 대화면 상세 분석",
          "개인 건강 → 팀/가족 통합 뷰",
        ],
        considerations: "Watch 데이터를 Mac 대화면에서 장기 트렌드로 분석하거나, 메뉴바에서 실시간 상태를 모니터링하는 패턴이 효과적입니다.",
        effort: 7,
        example: "Heart Analyzer — Watch 심박 데이터를 Mac 대화면에서 장기 트렌드 그래프로 분석",
      },
      iPadOS: {
        title: "watchOS → iPadOS",
        difficulty: "중간",
        approach: "데이터 시각화 + 운동 코치 뷰",
        keyChanges: [
          "작은 차트 → 대형 대시보드",
          "요약 정보 → 상세 데이터 테이블",
          "단순 UI → 인터랙티브 차트/그래프",
          "개인 뷰 → 코치/트레이너 공유 뷰",
        ],
        considerations: "iPad의 큰 화면은 Watch가 수집한 건강/피트니스 데이터를 시각적으로 풍부하게 표현하기에 이상적입니다. 운동 중 iPad를 거치대에 놓고 실시간 데이터를 보는 시나리오도 고려하세요.",
        effort: 5,
        example: "Nike Run Club — Watch로 달리기 추적, iPad에서 코스 지도와 상세 러닝 분석",
      },
      tvOS: {
        title: "watchOS → tvOS",
        difficulty: "중간",
        approach: "거실 피트니스 + 대형 화면 데이터",
        keyChanges: [
          "손목 데이터 → TV에 실시간 표시",
          "개인 운동 → 가족 함께 운동",
          "작은 화면 가이드 → 풀스크린 운동 가이드",
          "1인 트래킹 → 다인 경쟁/협력",
        ],
        considerations: "Watch의 실시간 센서 데이터를 TV 대형 화면에 표시하며 함께 운동하는 경험은 강력한 시너지를 만듭니다.",
        effort: 6,
        example: "Apple Fitness+ — Watch로 심박 측정, TV에서 운동 영상 + 실시간 수치 표시",
      },
      visionOS: {
        title: "watchOS → visionOS",
        difficulty: "높음",
        approach: "공간 건강 대시보드 + 몰입형 운동",
        keyChanges: [
          "2D 차트 → 3D 데이터 시각화",
          "화면 내 운동 → 공간 몰입 운동",
          "단순 알림 → 공간 오버레이 코칭",
          "개인 데이터 → 공간에 배치된 다중 지표",
        ],
        considerations: "Watch 센서 + Vision Pro 공간을 결합한 몰입형 피트니스가 가장 자연스러운 확장이지만, 아직 시장이 작아 ROI를 신중히 판단하세요.",
        effort: 8,
        example: "명상 앱 — Watch 심박 바이오피드백 + Vision Pro 몰입 환경으로 명상 경험 극대화",
      },
    },
  },
  tvOS: {
    icon: "📺", color: "#64D2FF", colorLight: "#F0FBFF",
    desc: "린백 콘텐츠 소비. 공유 대형 화면, 리모컨 UX.",
    expansions: {
      iOS: {
        title: "tvOS → iOS",
        difficulty: "중간",
        approach: "모바일 리모컨 + 개인 콘텐츠 관리",
        keyChanges: [
          "리모컨 UX → 터치 직접 조작",
          "공유 화면 → 개인 화면",
          "린백 감상 → 이동 중 감상",
          "대형 콘텐츠 → 모바일 최적화 콘텐츠",
        ],
        considerations: "TV 앱의 콘텐츠를 이동 중에도 이어볼 수 있는 핸드오프 경험이 핵심입니다. 또한 iPhone을 TV의 고급 리모컨/세컨드 스크린으로 활용하면 시너지가 큽니다.",
        effort: 5,
        example: "Netflix — TV에서 시청하다 외출 시 iPhone에서 이어보기, iPhone으로 콘텐츠 검색/큐 관리",
      },
      macOS: {
        title: "tvOS → macOS",
        difficulty: "중간",
        approach: "데스크톱 미디어 플레이어 + 관리 도구",
        keyChanges: [
          "리모컨 → 키보드/마우스 조작",
          "전체화면 → PiP/윈도우 모드",
          "단순 브라우징 → 라이브러리 관리",
          "가족 공유 → 개인 시청",
        ],
        considerations: "Mac에서는 '작업하면서 보기'(PiP)와 콘텐츠 라이브러리 관리에 초점을 맞추세요. TV의 풀스크린 몰입과는 다른 가치를 제공해야 합니다.",
        effort: 5,
        example: "Plex — TV에서 가족 시청, Mac에서 미디어 서버 관리 + PiP 재생",
      },
      iPadOS: {
        title: "tvOS → iPadOS",
        difficulty: "낮음",
        approach: "개인 시청 + 터치 브라우징",
        keyChanges: [
          "리모컨 → 터치 직접 조작",
          "고정 거실 → 휴대 가능",
          "공유 화면 → 개인 화면",
          "소파 거리 UI → 근거리 터치 UI",
        ],
        considerations: "iPad는 '개인 TV'로서 가장 자연스러운 확장입니다. 터치로 직접 콘텐츠를 탐색하고, 다운로드로 오프라인 시청을 지원하면 이동 시 강점이 됩니다.",
        effort: 3,
        example: "Disney+ — TV에서 가족 시청, iPad에서 개인 시청 + 다운로드 오프라인 감상",
      },
      watchOS: {
        title: "tvOS → watchOS",
        difficulty: "높음",
        approach: "리모컨 + 오디오 콘텐츠 전용",
        keyChanges: [
          "비디오 콘텐츠 → 오디오만 추출",
          "시각 브라우징 → 음성 제어",
          "대형 화면 → 손목 리모컨",
          "긴 감상 → 팟캐스트/음악 스트리밍",
        ],
        considerations: "영상 콘텐츠를 Watch로 가져가는 건 무리입니다. TV 리모컨 역할이나 오디오 콘텐츠(팟캐스트, 음악) 분리가 현실적인 방향입니다.",
        effort: 6,
        example: "Spotify — TV에서 스피커 연결 재생, Watch에서 리모컨/오프라인 러닝 플레이리스트",
      },
      visionOS: {
        title: "tvOS → visionOS",
        difficulty: "중간",
        approach: "개인 극장 + 공간 미디어",
        keyChanges: [
          "물리 TV → 가상 초대형 스크린",
          "고정 크기 → 자유 크기 조절",
          "2D 콘텐츠 → 공간 비디오/180° 콘텐츠",
          "거실 한정 → 어디서나 극장 경험",
        ],
        considerations: "TV의 콘텐츠 소비 경험을 개인 몰입형 극장으로 확장하는 것이 자연스럽습니다. 공간 비디오와 180° 콘텐츠는 TV에서 불가능한 차별화 포인트입니다.",
        effort: 5,
        example: "Apple TV+ — TV 시리즈를 Vision Pro에서 가상 극장 + 공간 오디오로 극대화",
      },
    },
  },
  visionOS: {
    icon: "🥽", color: "#AC8E68", colorLight: "#FAF6F0",
    desc: "공간 컴퓨팅. 시선/제스처 UX, 몰입형 경험.",
    expansions: {
      iOS: {
        title: "visionOS → iOS",
        difficulty: "중간",
        approach: "2D 모바일 버전 + AR 기능 활용",
        keyChanges: [
          "공간 배치 → 단일 화면 2D",
          "시선/핀치 → 터치 제스처",
          "3D 오브젝트 → ARKit으로 카메라 뷰",
          "몰입 환경 → 모바일 AR 오버레이",
        ],
        considerations: "visionOS의 공간 경험을 iPhone에서는 ARKit으로 부분적으로 재현하세요. 핵심 가치가 3D라면 AR Quick Look 등으로 맛보기를 제공하고, 풀 경험은 Vision Pro로 유도하세요.",
        effort: 6,
        example: "IKEA Place — Vision Pro에서 방 전체 가구 배치, iPhone에서 ARKit 단일 가구 미리보기",
      },
      macOS: {
        title: "visionOS → macOS",
        difficulty: "중간",
        approach: "2D 에디터 + 3D 미리보기",
        keyChanges: [
          "공간 UI → 전통 윈도우 UI",
          "제스처 → 마우스/키보드",
          "몰입 환경 → 3D 뷰포트 윈도우",
          "공간 오디오 → 스테레오/서라운드",
        ],
        considerations: "Vision Pro에서 경험하는 콘텐츠를 Mac에서 제작/편집하는 생산 도구 역할이 자연스럽습니다. 3D 프리뷰를 제공하되, 최종 경험은 Vision Pro에서 확인하도록 안내하세요.",
        effort: 5,
        example: "Reality Composer — Vision Pro에서 3D 경험을 시연, Mac에서 씬 편집/에셋 관리",
      },
      iPadOS: {
        title: "visionOS → iPadOS",
        difficulty: "낮음",
        approach: "2D 호환 + AR 기능 활용",
        keyChanges: [
          "공간 3D → 평면 2D + ARKit",
          "무한 캔버스 → 큰 화면 + 스크롤",
          "시선/핀치 → 터치/Pencil",
          "볼륨 렌더링 → 3D 뷰포트 위젯",
        ],
        considerations: "iPad는 visionOS 앱의 자동 호환 대상이므로, 반대 방향도 자연스럽습니다. iPad의 ARKit으로 3D 기능의 라이트 버전을 제공하세요.",
        effort: 3,
        example: "JigSpace — Vision Pro에서 실물 크기 3D 모델, iPad에서 AR 카메라 뷰로 3D 확인",
      },
      watchOS: {
        title: "visionOS → watchOS",
        difficulty: "매우 높음",
        approach: "알림/상태 모니터링 전용",
        keyChanges: [
          "공간 경험 → 단순 알림",
          "비주얼 리치 → 텍스트/아이콘만",
          "장시간 몰입 → 5초 글랜스",
          "복잡한 3D → 상태 인디케이터",
        ],
        considerations: "visionOS와 watchOS는 가장 거리가 먼 플랫폼 조합입니다. Watch는 'Vision Pro 세션이 끝났습니다', '공유 공간에 초대됐습니다' 같은 알림 역할로만 제한하세요.",
        effort: 4,
        example: "명상 앱 — Vision Pro 몰입 명상 종료 시 Watch가 햅틱으로 알림 + 심박 요약",
      },
      tvOS: {
        title: "visionOS → tvOS",
        difficulty: "중간",
        approach: "2D 공유 화면 버전 + AirPlay",
        keyChanges: [
          "개인 몰입 → 가족 공유 화면",
          "3D 공간 → 2D 대형 화면",
          "시선/핀치 → 리모컨 조작",
          "자유 배치 → 전체화면 고정",
        ],
        considerations: "Vision Pro의 개인 경험을 TV로 미러링/공유하는 시나리오가 핵심입니다. '내가 보는 것을 가족에게 보여주기' 관점으로 접근하세요.",
        effort: 5,
        example: "공간 사진 — Vision Pro에서 촬영한 공간 사진을 TV에서 2D 하이라이트로 가족과 감상",
      },
    },
  },
};
